[package]
name = "oranda-inference-test"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/oranda-gallery/oranda-inference-test"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
